### ISSUE TITLE
parts looks black and not found in ANY catagory

### ISSUE THREAD

**Issue by Ristellise** [MagicSmokeIndustries/IR-ModelRework#14]

**Comment by ZiwKerman** [comment]
Could you please post your output_log.txt here, so we can check?

**Comment by Ristellise** [comment]
I will post it later. I am currently out

**Comment by ZiwKerman** [comment]
Have you installed latest version of IR Plugin rework from here? http://forum.kerbalspaceprogram.com/threads/114014-WIP-MSI-s-Infernal-Robotics-Plugin-Rework-%28Updated-05-04-2015%29

**Comment by Ristellise** [comment]
Yes.

**Comment by Ristellise** [comment]
Soo how to install 
1. Main IR from release thread
2. Plugin rework
3. Model rework
Correct?

**Comment by ZiwKerman** [comment]
You only need 2. and 3.

**Comment by ZiwKerman** [comment]
Please try backing up your old MagicSmokeIndustries folder somewhere outside of your GameData folder and make a clean install of 2. and then 3.

**Comment by Ristellise** [comment]
I cleaned the folder (deleted it)
Then I install plugin rework
then model rework but still have problems. Tge icons  are STILL black....

**Comment by ZiwKerman** [comment]
So now you see the parts in the custom category, but the parts are black?

**Comment by Ristellise** [comment]
When I get home ( still out) I will boot up ksp and get the log file okay?

**Comment by ZiwKerman** [comment]
Try cleaning the Active Texture Management cache - delete folder texture cache (or something like that) inside GameData/Active Texture Management.

**Comment by Ristellise** [comment]
ah..  the fixing of texture fixes the black parts!
now how to fix parts not found in any catagory?

**Comment by ZiwKerman** [comment]
Please post your log, it seems some errors from other mods interfere with our custom category loading

**Comment by Ristellise** [comment]
I have quick search. Does it affect?

**Comment by Ristellise** [comment]
http://pastebin.com/8bKSCAG4

**Comment by ZiwKerman** [comment]
It does not seem like a complete log. Can you zip the full log and post it somewhere on google docs or something?

**Comment by Ristellise** [comment]
https://www.dropbox.com/s/ewj3qn36i2x6dsj/output_log.txt?dl=0
Okay here should be the complete log.

**Comment by ZiwKerman** [comment]
It is a hell of a log. It is really hard to find anything. Could you try to reproduce an a cleaner install, with just KIS, FilterExtensions and IR, as these are the only ones messing with categories.

**Comment by Ristellise** [comment]
i think it is quick search that is causing bugs

**Comment by ZiwKerman** [comment]
I have quicksearch and it works fine. But if you can check it on your
machine it would be nice.

On Monday, April 13, 2015, Joshwoo69 notifications@github.com wrote:

> i think it is quick search that is causing bugs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MagicSmokeIndustries/IR-ModelRework/issues/14#issuecomment-92321202
> .

## 

Best regards,
Stepan Andreev

**Comment by Ristellise** [comment]
hmm quick search is fine...

**Comment by Ristellise** [comment]
should i give you my mod list?

**Comment by Ristellise** [comment]
maybe you should have a MM patch to resolve ALL of this ;)

**Comment by ZiwKerman** [comment]
Can you try clean install with just 3 mods - KIS, FilterExtensions and IR?

On Mon, Apr 13, 2015 at 1:43 PM, Joshwoo69 notifications@github.com wrote:

> maybe you should have a MM patch to resolve ALL of this ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MagicSmokeIndustries/IR-ModelRework/issues/14#issuecomment-92340047
> .

## 

Best regards,
Stepan Andreev

**Comment by Ristellise** [comment]
tried. have result of a new robotic part catagory

**Comment by ZiwKerman** [comment]
aha, so it is something else in your install.

Unfortunately the best way to check is to do a binary search for conflicting mod:

1) move half of the mods you have into a separate folder and try it again
2) if it works - add half of the removed mods back and check again
if it does not - repeat 1)

**Comment by Ristellise** [comment]
i would close this with a MM patch to fix this
