### ISSUE TITLE
Symmetry issues

### ISSUE THREAD

**Issue by Tbone11223** [MagicSmokeIndustries/IR-ModelRework#23]
There is an issue when putting symmetry on for any of the new parts. It's a little hard to explain so i'll do it with screenshots, but here's a rundown of my problem... I'm trying to make an internal weapons bay that I can use as a sub-assembly to stick on just about any aircraft I want, in the screenshots is a concept design test; as you can see the weapons bay on the right side of the craft is normal and I have made fine adjustments and tuning to the servos/moving parts to achieve this design. But, the opposite one to the original (when using symmetry) seems to have thrown all that fine tuning out the window and goes back to its default configuration. It would be greatly appreciated if this problem could be addressed so that when using symmetry, it saves all the tuning to the moving parts that the player has made (i.e. when right clicking the part in the editor and moving the sliders to get what you want).

On a side note, would it be possible to add some parts that make weapon bays easier to build?

Thanks

![ksp 2015-04-25 13-15-19-02](https://cloud.githubusercontent.com/assets/12107585/7331350/bacbd934-eb4e-11e4-8f1b-332c4757da99.jpg)
![ksp 2015-04-25 13-13-07-22](https://cloud.githubusercontent.com/assets/12107585/7331345/a0742852-eb4e-11e4-915a-e01518ac04ce.jpg)
![ksp 2015-04-25 13-15-07-09](https://cloud.githubusercontent.com/assets/12107585/7331347/a9963876-eb4e-11e4-80ea-50ebb531d977.jpg)
![ksp 2015-04-25 13-13-13-61](https://cloud.githubusercontent.com/assets/12107585/7331348/acf3ffe4-eb4e-11e4-85e3-09e0e650f69a.jpg)

**Comment by ZodiusInfuser** [comment]
I'm not sure how you managed to do that. In all my testing I've not experience any issues with symmetry of parts not behaving right.

As for the latter point. What did you have in mind? I may have something in the works that would be suitable.

**Comment by Tbone11223** [comment]
Well I was thinking about maybe adding something like the Mk 2 cargo bays, except there are smaller spaces where you could fit weapons (from BDArmory). Think of it as a F-22 weapons bay embedded into the Mk 2 fuselage.

**Comment by ZodiusInfuser** [comment]
Looked at the image again. You're using a rotatron for the opening of the bay. I would suggest switching to a hinge part.
