### ISSUE TITLE
Texture problem

### ISSUE THREAD

**Issue by Ivans81** [MagicSmokeIndustries/IR-ModelRework#24]
The mod works great until I shut the game down. When I restart the game all the parts load in black. All the part still work. It also does this when I add a new mod. Mod List: Aggressive-Release, Airbags_0.4.0,  Bacon Labs Stockalike Ariane 0.3.1, ChopShop_0.7.0, HeatWarning, IR_v0.21.1 Infernal_Robotics_Model_Rework_-_Core_Pack-v01b, Infernal_Robotics_Model_Rework_-_Expansion_Pack-v01b, Kduffers_Korp-0.11, Kerbal_Joint_Reinforcement-v3.1.3, KerbalEngineer-1.0.16.3, RasterPropMonitor.0.19.0, ScienceAlert-1.8.5, StockBugFixModules.v1.0.0, TransferWindowPlanner_1.3.0.0, TweakableEverything-1-9, VNG-Parachute_1.2. If its a mod conflict then the other mod is gone. IR is one of the top five most essential mod for KSP. If u need a sreen shot let me know.

**Comment by ZiwKerman** [comment]
It seems that we have some incompatibility with ATM. Deleting the cache should help, we'll work on that too.

**Comment by Ivans81** [comment]
Thanks I thought it might be that. Thanks for the fast response and keep up the great work.

**Comment by enceos** [comment]
Anyone recognizes this image? :D

![Dummy](http://i.imgur.com/z2PYNrG.jpg)

**Comment by BaronZer0** [comment]
Add this to the OVERRIDE option in the
_ActiveTextureManagement/ActiveTextureManagementConfigs/MagicSmokeIndustries_ file:

```
MagicSmokeIndustries/Parts/.*
{
    compress = true
    mipmaps = true
    scale = 1
    max_size = 0
}
```

and delete the _ActiveTextureManagement/textureCache/MagicSmokeIndustries_ folder.
At least it worked for me.

**Comment by ZodiusInfuser** [comment]
I am closing this as issues with ATM are outside of the scope of my mod.
