### ISSUE TITLE
bulkheadProfiles

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [MagicSmokeIndustries/IR-ModelRework#27]
Since the rework's parts are meant to be single-size, it's important that their bulkheadProfiles are defined in order to let them be sorted where they ought to be.  Most of them should have "bulkheadProfiles = size0, srf" (since they're size 0 and surface-attachable), but some of the parts with "mini" ends on them could also reasonably be sorted into the size "00" custom category that I'll be defining for FilterExtensions (more details [over here](http://forum.kerbalspaceprogram.com/threads/121898-PSA-bulkheadProfiles-and-you-and-a-request-for-comments-requests-what-cross-sections-do-you-want?)).

**Comment by ZodiusInfuser** [comment]
Ok. for now I'll add bulkheadProfiles = size0, srf to all the relevant parts, and then see about updating them to filter extension variants in the future.

**Comment by ZodiusInfuser** [comment]
Added this to all parts in the latest pre-release.
