### ISSUE TITLE
Uncontrolled Servos/Hinges

### ISSUE THREAD

**Issue by K-re** [MagicSmokeIndustries/IR-ModelRework#28]
I came up with these ideas when trying to make a mobile crane that used KAS winches and lines as  structural elements and control of the reach. 

Issues:
1) Angles cannot be changed in VAB/SPH
2) Angles cannot be locked in VAB/SPH, Inflight nor EVA
3) Angle Limits cannot be set 

Rationale for suggested changes to all uncontrolled servos:
1) A free hinge which is useful for a design, may not be easily implemented because the angle cannot be selected or changed as the model may require.

2) A hinge angle cannot be "locked" to a specific angle without using struts. I think that to keep the mod balanced, Locking should be an EVA activity, as well as a VAB/SPH. 

3) If you use the previous two suggestions this is the natural progression. Limits should be available to prevent over-rotation, as defined by the user. This should only be available in the VAB/SPH for balance/realism.

Lastly, Thank You All for this and the complimentary mods. They have kept me busy for hours and hours.

**Comment by ZodiusInfuser** [comment]
Locking and angle limits of Uncontrolled joints is not possible due to the way the plugin works. Having angle changeable in VAB could be explored though, but you'll need to post the issue over in: https://github.com/MagicSmokeIndustries/InfernalRobotics
