### ISSUE TITLE
Consider creating Controller part

### ISSUE THREAD

**Issue by ZiwKerman** [MagicSmokeIndustries/IR-ModelRework#29]
Something that includes kOSPorcessur module, command module (probe core) and Sequencer storage.

Visuals might be be borrowed from here

![image](https://cloud.githubusercontent.com/assets/11242352/11938874/d08bc75a-a815-11e5-9724-881b474a3039.png)

**Comment by ZodiusInfuser** [comment]
Done and pre-released.
